### ISSUE TITLE
Make test failing : deploy declared but not used

### ISSUE THREAD

**Issue by coreydaley** [openshift/cluster-image-registry-operator#104]
Oleg, 
Since you added this test could you check this out?
Not sure how it got merged with this test failing either?

https://github.com/openshift/cluster-image-registry-operator/blob/master/test/e2e/recreate_deployment_test.go#L50

# github.com/openshift/cluster-image-registry-operator/test/e2e_test
test/e2e/recreate_deployment_test.go:50:2: deploy declared but not used
vet: typecheck failures
FAIL	github.com/openshift/cluster-image-registry-operator/test/e2e [build failed]
make: *** [Makefile:24: test-e2e] Error 2

**Comment by dmage** [comment]
This will be fixed by https://github.com/openshift/cluster-image-registry-operator/pull/98/files

**Comment by bparees** [comment]
i've merged the fix but i'm not sure how the original PR passed testing either.  I manually merged it, but only after it had passed e2e-aws-operator.

**Comment by dmage** [comment]
Did it fail in our CI?
