### ISSUE TITLE
Extract 'testframework' into openshift/library-go

### ISSUE THREAD

**Issue by jhadvig** [openshift/cluster-image-registry-operator#125]
We want to reuse the [testframework](https://github.com/openshift/cluster-image-registry-operator/tree/master/pkg/testframework)  for our the [console-operator](https://github.com/openshift/console-operator) e2e tests. Is there any plan to refactor and extract it into https://github.com/openshift/library-go ?

**Comment by bparees** [comment]
Not any time soon. We need to be able to move faster right now than that
would allow.

Ben Parees | OpenShift
