### ISSUE TITLE
clusteroperator condition message improvements

### ISSUE THREAD

**Issue by bparees** [openshift/cluster-image-registry-operator#126]
slack exchange:

> i’d like to get some style cleanups in both the devex team operators on the progressing message
> this is your primary communication channel and the intended receiver is the admin
> right now it’s “The samples operator configuration is valid” and for registry it’s something slightly more machine oriented
> i’d like the message to be something more affirmative like “The latest sample images and templates are installed” or something
> or even shorter “All sample resources are up to date”
> the style is sentence without punctuation
> upper case leading, no punctution, human intended receipient
> try to avoid kube-isms and overly technical explanations
>
> Gabe Montero [1:41 PM]
> the available condition is the one that says "Samples exist in the openshift project"
>
> Clayton Coleman [1:42 PM]
> Progressing is the generic condition
>
> Gabe Montero [1:42 PM]
> the failing condition is the one that says ""The samples operator configuration is valid""
>
> Clayton Coleman [1:43 PM]
> that’s where you put your human focused summary message
> Progressing must represent a summary of the other conditions
> so it’s fine to have the same message on progressing as available
> (it’s fine to have the same messages on available)
> but available and failed should explain the details as necessary, while progressing should explain to a human what the current state is

> For context see https://github.com/openshift/cluster-version-operator/blob/master/pkg/cvo/status.go which has comments and examples of how the CVO works which is what this pattern is modeled on.

> https://github.com/openshift/cluster-version-operator/pull/72 is docs around what to do

This came from https://github.com/openshift/cluster-samples-operator/issues/69

so see that issue for additional discussion.

**Comment by gabemontero** [comment]
If you read between the lines with https://github.com/openshift/cluster-version-operator/blob/master/docs/dev/clusteroperator.md#conditions .... it is mandating enough version maintenance to deal with release to release migration, as it highlights situations when you operator's current status reflects what was done at at say 4.0.0, but your operator's image payload is now 4.0.1, it has triggered a new deployment of your operator, and you need to report that you are trying to get to a 4.0.1 state.

At least with the samples operator, I'm having to make changes to properly handle that.

**Comment by dmage** [comment]
The messages were improved by #246.
