### ISSUE TITLE
unncessary updates to the CR

### ISSUE THREAD

**Issue by bparees** [openshift/cluster-image-registry-operator#134]
This code:

https://github.com/openshift/cluster-image-registry-operator/blob/6e2fee7776e3fc671cc90fe783000095e6927fad/pkg/resource/generator.go#L233-L248

means that we are ultimately going to update the CR even if we haven't necessarily changed the CR itself as part of an event loop (we may have only updated a secondary resource). 

Every time we update the CR, we trigger an event that sends us back through the generator logic, so this means at a minimum we're doing one extra event loop process every time.

**Comment by dmage** [comment]
For the custom resource we can use the same approach as we use for other resources: check if the resource from the lister matches the expected state.

**Comment by coreydaley** [comment]
@dmage can you point me to some existing code that is doing that in the operator?

**Comment by coreydaley** [comment]
@dmage nevermind, found it

**Comment by dmage** [comment]
Fixed by #192.
