### ISSUE TITLE
registry-ca-hostmapper should run on linux only nodes

### ISSUE THREAD

**Issue by derekwaynecarr** [openshift/cluster-image-registry-operator#138]
similar to the following:
https://github.com/openshift/cluster-dns-operator/pull/67/files

cc @mrunalp

**Comment by bparees** [comment]
@mrunalp @runcom you guys own the daemonset definition at this point:
https://github.com/openshift/cluster-image-registry-operator/blob/master/pkg/resource/nodecadaemon.go#L20

**Comment by mrunalp** [comment]
Yeah we will take care of this.

**Comment by mrunalp** [comment]
I will make a PR.
