### ISSUE TITLE
operator is hotlooping when s3 storage is configured

### ISSUE THREAD

**Issue by bparees** [openshift/cluster-image-registry-operator#140]
Evidenced by the quickly scrolling list of events being handled in the operator log.  Changing to emptydir storage stops the hotloop.

**Comment by coreydaley** [comment]
Looks like #137 will cut the requests in half (or a little more).  That should help for now but probably still requires a bit more digging after that pr merges.

**Comment by bparees** [comment]
yeah this is not about how many requests are being made for a given event. it's about the operator being in a continuous loop of:

0) get event for something being updated
1) update something (likely the CR)
2) goto (0)

**Comment by coreydaley** [comment]
Just sent you an email ;)

**Comment by coreydaley** [comment]
This was fixed by #137
