### ISSUE TITLE
Organize tests in test/e2e into well defined packages

### ISSUE THREAD

**Issue by coreydaley** [openshift/cluster-image-registry-operator#151]
Test timeouts (default of 10 minutes) are applied on a per package basis.  If we organize the tests into proper packages we can go back to using the default timeout.

**Comment by bparees** [comment]
until one of the packages gets big enough to need a larger timeout by itself.

**Comment by dmage** [comment]
Having different packages will eliminate TestMain, i.e. the entry point that can prepare environment (disable CVO for our operator, for example).

**Comment by bparees** [comment]
Well, unless we put a TestMain in every package, right?

(it can even wrapper a shared implementation so they are kept in sync)

**Comment by dmage** [comment]
Yes, we can put in in every test. Maybe it's better approach.

**Comment by bparees** [comment]
@coreydaley what's the basis for closing this?
