### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by gustavonalle** [openshift/cluster-image-registry-operator#157]
Guess it's more a clarification request than an issue or bug, but how does the internal pods manage to pull images from the registry?

I have a situation where I installed the registry operator, I can push and pull images from outside openshift, but when I try ```oc new-app namespace/image``` the pods simply cannot pull the image from the registry.
First there is a certificate error (Unknown issuer) that I solved by copying the image registry certificate to ```/etc/docker/certs.d/<host>``` inside each node, but then it starts to fail with 

```
Failed to pull image [...] rpc error: code = Unknown desc = unauthorized: authentication required
```

The image registry pod itself implies the pods is trying to pull images anonymously:

```
time="2019-01-15T19:12:26.189081838Z" level=error msg="OpenShift access denied: no RBAC policy
 matched" go.version=go1.10.3 openshift.auth.user=anonymous vars.name=default/fedoraa 
vars.reference="sha256:d79ddffdce8112f111878afcbe0205ef43e3eead131399194e2cf66fa8f3e5ed"
```

So my question is, what is the expect way to use the registry operator? Does it require extra configurations beyond what is https://github.com/openshift/cluster-image-registry-operator/tree/master/deploy ?

**Comment by bparees** [comment]
Yes, this operator must be used in conjunction with a 4.0 cluster installed by the new openshift installer, there are other required pieces that are managed by other operators. We are not going to support use cases where you manually deployed this operator in a cluster.
