### ISSUE TITLE
encryption being applied to user provided buckets

### ISSUE THREAD

**Issue by bparees** [openshift/cluster-image-registry-operator#160]
based on this:

https://github.com/openshift/cluster-image-registry-operator/blob/7f6ffaf58e512d193e8de4d683783921f59f3797/pkg/storage/s3/s3.go#L365-L377

it looks like we apply our own encryption settings to the s3 bucket even if the bucket was supplied by the user, even if the bucket already existed.  This means a user can't provide their own s3 bucket w/ their own encryption settings.

**Comment by coreydaley** [comment]
@bparees 
Do we want to skip the [tagging](https://github.com/openshift/cluster-image-registry-operator/blob/master/pkg/storage/s3/s3.go#L339-L363) and the [bucket lifecycle configuration](https://github.com/openshift/cluster-image-registry-operator/blob/master/pkg/storage/s3/s3.go#L388-L417) (cleanup incomplete multipart uploads) also if we did not create the bucket?

**Comment by bparees** [comment]
Yeah i think that makes sense. If they just named it and we created it, we should do those things. But if the bucket was not created by us, don't touch it.
