### ISSUE TITLE
Write tests for AdditionalTrustedCA

### ISSUE THREAD

**Issue by dmage** [openshift/cluster-image-registry-operator#214]
Recently we had a regression (#205). We need to have a test for AdditionalTrustedCA to avoid such regressions in the future.

**Comment by adambkaplan** [comment]
In origin we have unit tests for the sync of the CA content for the build controller: https://github.com/openshift/origin/blob/master/pkg/build/controller/build/build_controller_test.go#L1244.
We may be able to go a step further and add an operator e2e test that verifies the registry has the correct configuration loaded.

Full e2e is impossible without spinning up a separate registry.
