### ISSUE TITLE
don't use GC for PVC cleanup

### ISSUE THREAD

**Issue by bparees** [openshift/cluster-image-registry-operator#216]
I'm removing most of our GC usage here:
https://github.com/openshift/cluster-image-registry-operator/pull/215

but I don't want to get into the PVC logic.  Right now it appears to be using GC to ensure the PVC gets removed when the CR is removed.  That won't work because the CR is cluster-scoped and GC can't span namespaces.  The PVC needs to be cleaned up via finalization.

**Comment by bparees** [comment]
looks like the PVC should already be cleaned up by the finalizer, so we can just drop the ownerref.  I've done so in https://github.com/openshift/cluster-image-registry-operator/pull/215

**Comment by legionus** [comment]
@bparees I use the ownerref in PVC not for GC. I need to detect that PVC was not created by the operator. It seems to me wrong to create a new field in the CR status when for this purpose we have an ownerref already.

**Comment by bparees** [comment]
> @bparees I use the ownerref in PVC not for GC. I need to detect that PVC was not created by the operator. It seems to me wrong to create a new field in the CR status when for this purpose we have an ownerref already.

as far as i know, you can't have an ownerref w/o it being used for GC.  If you create an ownerref, GC will attempt to follow that ownerref and GC you if it does not exist.  And when that ownerref points to a clusterscoped resource, the results are indeterminate.

So unless i'm wrong, you can't use it that way and you'll have to introduce an annotation in the same way that I did for routes.

**Comment by legionus** [comment]
@bparees as you wish.

**Comment by bparees** [comment]
> @bparees as you wish.

Does it make sense why we cannot use ownerrefs here?

**Comment by legionus** [comment]
@bparees Yes, it doesn't make sense to me, but I can handle it. PR is ready.
