### ISSUE TITLE
TestAWSUnableToCreateBucketOnStartup InvalidAccessKeyId errors during tests

### ISSUE THREAD

**Issue by coreydaley** [openshift/cluster-image-registry-operator#221]
message: "Unable to apply resources: unable to sync storage configuration: InvalidAccessKeyId:
		      The AWS Access Key Id you provided does not exist in our records.\n\tstatus
		      code: 403, request id: 9F7CF2E209519A53, host id: KmxOvvgpisxuwNCxf8xm3HQSKHryoECU6n10p2YUQBiW3sytZYtUmny006BW5ypF47nYQTzVSzE="
		    status: "True"

**Comment by bparees** [comment]
seen here:

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_cluster-image-registry-operator/222/pull-ci-openshift-cluster-image-registry-operator-master-e2e-aws-operator/1199/

**Comment by bparees** [comment]
I am disabling this test in https://github.com/openshift/cluster-image-registry-operator/pull/222/commits/fe0ec949846cfe03c2d125174126cfa4c5048a01 so we can unblock our queue.  Please fix+reenable the test asap.
