### ISSUE TITLE
wrong creds log message

### ISSUE THREAD

**Issue by bparees** [openshift/cluster-image-registry-operator#228]
this is logging the wrong namespace:
https://github.com/openshift/cluster-image-registry-operator/blob/master/pkg/clusterconfig/clusterconfig.go#L123

```
"Unable to apply resources: unable to sync storage configuration: unable to get cluster minted credentials \"kube-system/installer-cloud-credentials\": timed out waiting for the condition",
```

it's not looking in kube-system, it's looking in openshift-image-registry.

probably worth double checking others as well.

**Comment by coreydaley** [comment]
Closed via #229
