### ISSUE TITLE
enable must-gather object refs

### ISSUE THREAD

**Issue by bparees** [openshift/cluster-image-registry-operator#231]
If the clusteroperator defines object refs, the must-gather tool can automatically collect relevant resources/logs/etc from the references objects/namespaces.  See:

https://github.com/openshift/cluster-openshift-controller-manager-operator/pull/76/files#diff-ef02f4dd56d4bd19d7b3e4913b9a57d5R82

This operator should be updated to define appropriate object references.

/cc @dmage @adambkaplan

**Comment by dmage** [comment]
https://jira.coreos.com/browse/DEVEXP-297
