### ISSUE TITLE
[api-freeze] Verify operator API is frozen

### ISSUE THREAD

**Issue by adambkaplan** [openshift/cluster-image-registry-operator#256]
*Backwards compatibility of GA APIs*

What constitutes a backwards compatible API?

1. Fields can not be removed (this also means you can’t rename a field)
2. Serialized defaults can not change.  Unserialized defaults in operators can change over time.
3. Behavior (meaning) of a field can not change.  This means that old fields must be maintained even if new fields supercede them.
4. New fields can be introduced that supercede existing fields, but values in the existing fields must be respected when present.

Other things that should be considered “API”

1. Names of singleton CRs in openshift-config (user-provided) and openshift-config-managed (operator-provided) namespaces that are used for cross-communication of components
2. Names / namespaces of Services used for cross-communication of components
3. Annotations and labels used for cross-communication of components

/assign @dmage

**Comment by adambkaplan** [comment]
@dmage there are a few areas of concern with the API:

1. A TODO regarding the "Removed" status type: https://github.com/openshift/cluster-image-registry-operator/blob/master/pkg/apis/imageregistry/v1/types.go#L49-L51
2. Storage types for Azure, GCS, and Swift/OpenStack are present. These won't be ready for GA until 4.2 at minimum. https://github.com/openshift/cluster-image-registry-operator/blob/master/pkg/apis/imageregistry/v1/types.go#L194-L209
3. We have a catch-all "Filesystem" storage. https://github.com/openshift/cluster-image-registry-operator/blob/master/pkg/apis/imageregistry/v1/types.go#L221 IMO we should do one of two things here:
  a) Keep, but rename to "UnsupportedFilesystem" to make it clear that we do not provide support.
  b) Remove, and add an API field that allows EmptyDir storage for libvirt

@bparees @jwforres @openshift/sig-developer-experience fyi

**Comment by dmage** [comment]
Moved to https://bugzilla.redhat.com/show_bug.cgi?id=1700487
