### ISSUE TITLE
Use bindata to populate operand defaults

### ISSUE THREAD

**Issue by adambkaplan** [openshift/cluster-image-registry-operator#261]
Consider using `go-bindata` to load templates of the components managed by the cluster-image-registry-operator. This is a common practice amongst other OpenShift core operators - e.g. [ocm-o](https://github.com/openshift/cluster-openshift-controller-manager-operator/tree/master/bindata/v3.11.0/openshift-controller-manager).

Not required for 4.1

**Comment by dmage** [comment]
Which generator do you want to replace with a static file?

**Comment by adambkaplan** [comment]
If we choose to go down this path (and I'd argue this is lower-priority tech debt), I'd start with the resources that aren't impacted by the operator config, such as RBAC, the internal service, etc.

Downside is this introduces dual paths for implementing the same behavior if say the Deployment needs the generator.

**Comment by dmage** [comment]
Fixed by #436.
