### ISSUE TITLE
[openstack] should not use hard code 'openstack' cloud 

### ISSUE THREAD

**Issue by jichenjc** [openshift/cluster-image-registry-operator#303]
/bug

https://github.com/openshift/cluster-image-registry-operator/blob/52dfda7/pkg/clusterconfig/clusterconfig.go#L194

made assumption that the 'openstack' cloud is in cloud defintion but that's not always true and lead to https://github.com/openshift/installer/pull/1858 having issue in pass CI test

**Comment by mandre** [comment]
cc @Fedosin

**Comment by adambkaplan** [comment]
@jichenjc can there be more than one entry in the clouds.yaml map? If so, which one should the registry choose?

**Comment by jichenjc** [comment]
@adambkaplan yes, that's possible, it's asked when doing install config here:
https://github.com/openshift/installer/blob/master/pkg/asset/installconfig/openstack/openstack.go#L28
and it should be stored in manifests/cloud config as well...

**Comment by adambkaplan** [comment]
@abhinavdahiya @wking can admins specify more than one cloud for IPI or UPI installs? If yes, where should the registry provision storage?

**Comment by abhinavdahiya** [comment]
> @abhinavdahiya @wking can admins specify more than one cloud for IPI or UPI installs? If yes, where should the registry provision storage?

No, the admins can only choose one platform.

**Comment by jichenjc** [comment]
from my test , user can have a clouds.yaml, and it can contains more than 1 cloud and install process (install-config) will ask for which one to select to install cluster onto and it's not always `openstack` 
@adambkaplan

**Comment by abhinavdahiya** [comment]
> from my test , user can have a clouds.yaml, and it can contains more than 1 cloud and install process (install-config) will ask for which one to select to install cluster onto and it's not always `openstack`
> @adambkaplan

I think you need to clearly distinguish between platform ie AWS, Azure, OpenStack and OpenStack specific cloud value while I think you are talking about...

**Comment by jichenjc** [comment]
you are right @abhinavdahiya ,that's the reason why I mark the issue's title as [openstack]... thanks for pointing that out ,and yes, it's openstack only

**Comment by dmage** [comment]
Should we use the installer config to get the cloud name?

**Comment by jichenjc** [comment]
I think conceptually yes, but I might need more time if I did into code and find how to fix it :)

**Comment by adambkaplan** [comment]
@jichenjc are we still blocking https://github.com/openshift/installer/pull/1858?

We need resolution as to which cloud provider config to choose, or should we fail if the clouds.yaml file has more than one entry?

**Comment by jichenjc** [comment]
yes, I think we do, I am not expert in this area so I don't know whether we can get the value from somewhere to use given cloud, if we really can't , then only accept only cloud might works but seems not that good to me... thanks

**Comment by adambkaplan** [comment]
@abhinavdahiya @Fedosin @openshift/openshift-team-installer can you weigh in please?

**Comment by dmage** [comment]
As we moved away from the installer config, we need to have the cloud name in the Infrastructure resource: openshift/installer#1986
