### ISSUE TITLE
Swift test missing AssertNoErr, throws error if added

### ISSUE THREAD

**Issue by coreydaley** [openshift/cluster-image-registry-operator#330]
It looks like this section of code (https://github.com/openshift/cluster-image-registry-operator/blob/master/pkg/storage/swift/swift_test.go#L630-L638) is missing a th.AssertNoErr.  It looks like all of the others have it and that this is an omission, but if the th.AssertNoErr is added, the test fails with "Incorrect Auth URL", at that point the variable `path` equals /v/3/

Ran into this while de-duplicating some of the code in that test, for this specific reason, it's easy to miss something small like this, especially if it makes the test pass.

**Comment by coreydaley** [comment]
@Fedosin Could you please take a look at this test and see what it should do here?

**Comment by dmage** [comment]
@coreydaley this case tests asserts `err != nil`, i.e. it expects to get an error.

**Comment by coreydaley** [comment]
Doh, thanks!
/close
