### ISSUE TITLE
Default to Removed for bare metal infrastructure platform

### ISSUE THREAD

**Issue by russellb** [openshift/cluster-image-registry-operator#375]
This is a todo item from discussion in #332 

We currently default to emptyDir for the bare metal infrastructure platform.  This allows a successful install, but assumes the registry will be re-configured post-install before use.  

Once the image registry operator can be bootstrapped in a `Removed` state, we should use that instead.  That is a better reflection of the desired state at install time.

**Comment by dmage** [comment]
Closed by #392.
