### ISSUE TITLE
RFE - Provide a 'storage' option that allows me to set the specific StorageClass for the registry

### ISSUE THREAD

**Issue by nnachefski** [openshift/cluster-image-registry-operator#389]
I'm deploying Openshift 4.2 pre-release.  For storage, i'm deploying rook-ceph v1.1.1 (csi-cephfs & csi-rbd).  I want to set my rook-ceph-block(rbd) StorageClass to default.  But, csi-cephfs is the only storage that supports RWX (for registry pod).  I need a way to tell the registry operator to use a specific storageclass (not the default).  Right now, i have to do something less elegant to get the storage carved out the way i need it.  For instance:

> $OC_CLIENT patch storageclass csi-cephfs -p '{"metadata": {"annotations": {"storageclass.kubernetes.io/is-default-class": "true"}}}'
> sleep 15 
> $OC_CLIENT patch configs.imageregistry.operator.openshift.io cluster --type merge --patch '{"spec":{"storage":{"pvc":{"claim":""}}}}'
> sleep 30
> $OC_CLIENT patch storageclass csi-cephfs -p '{"metadata": {"annotations": {"storageclass.kubernetes.io/is-default-class": "false"}}}'
> $OC_CLIENT patch storageclass rook-ceph-block -p '{"metadata": {"annotations": {"storageclass.kubernetes.io/is-default-class": "true"}}}'
> sleep 30
> $OC_CLIENT create -f ../prometheus-rook.yml`

This is hack-ish and makes me sad.  I would love an option to specify the storageclass for my registry pvc.

**Comment by dmage** [comment]
@nnachefski you can create your own PVC in the openshift-image-registry namespace and use its name in `spec.storage.pvc.claim`. Have you tried it?

**Comment by adambkaplan** [comment]
@dmage I think there may be a larger issue here. If `pvc.claim` is not set, does the registry operator assume the default storage class will provision `RWX` storage? If so, is this assumption true on most providers?

**Comment by dmage** [comment]
@adambkaplan `RWX` is not an assumption, it is a requirement. The operator doesn't assign any storage classes, there is another component that sets the storage class to our PVC. The storage class isn't the only option than customers may want to change in PVC, there are also storage requests, selectors. And the bootstrapped PVC is read-only and can't be changed, so there is no reason to add parts of PVC to our configuration resource.

**Comment by bparees** [comment]
I think @adambkaplan is referring to the case where the operator creates the PVC itself.  When it does so, it sets RWX as required:
https://github.com/openshift/cluster-image-registry-operator/blob/master/pkg/storage/pvc/pvc.go#L132-L134

so i believe we are fine on that front.

**Comment by nnachefski** [comment]
Could something similar be done like with the Prometheus stack?  It uses a config map to configure the cluster-monitoring operator.

Ex:

apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    prometheusK8s:
      volumeClaimTemplate:
       spec:
         storageClassName: rook-ceph-block 
         resources:
           requests:
             storage: 40Gi

**Comment by bparees** [comment]
we generally have a preference for first class config apis (CRDs) over configmaps that are harder to validate, provide api documentation for, and enforce rbac rules around.

**Comment by tux-o-matic** [comment]
How is RWX a requirement when for years Docker said not to use NFS (commonly used RWX backend) at the risk of getting a corrupted registry? At least there should be a warning in the doc not to use NFS but CephFS or GlusterFS.

**Comment by dmage** [comment]
@tux-o-matic do you have a link where Docker says not to use NFS?

RWX is a requirement to avoid downtime during upgrades. In general, you should use an object storage (S3, GCS, etc.). PVC is an option when you don't have any object storage.

In 4.4 you can provide a RWO volume if you don't need a high available cluster.

**Comment by tux-o-matic** [comment]
@dmage One such [warning in 3.1 doc](https://docs.openshift.com/container-platform/3.11/scaling_performance/optimizing_storage.html#logging)
And another [caution](https://docs.openshift.com/container-platform/3.11/install_config/registry/registry_known_issues.html#known-issue-nfs-image-push-fails)

**Comment by aizuddin85** [comment]
@tux-o-matic NFSv3 might have such issue, but I believed NFSv4 already fixed those cache and other issue to make NFS more reliable when RWX mounted on many nodes.

**Comment by tux-o-matic** [comment]
@aizuddin85 , if that's the case then I think it should be mentioned in the documentation because I believe most people still stuck with NFS in their infrastructure are likely stuck with v3.x

**Comment by aizuddin85** [comment]
@tux-o-matic In the documentation it mentioned both. I agree we probably can make it clearer,  caveats between NFSv3 vs NFSv4.

**Comment by dmage** [comment]
The expected way to use a custom storage class is to provide your own PVC:
```
$ cat pvc.yaml
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: cephfs-storage
    namespace: openshift-image-registry
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 100Gi
    storageClassName: csi-cephfs
    volumeMode: Filesystem
$ oc apply -f pvc.yaml
persistentvolumeclaim/cephfs-storage created
$ oc patch configs.imageregistry.operator.openshift.io/cluster --type merge --patch '{"spec":{"storage":{"pvc":{"claim":"cephfs-storage"}}}}'
config.imageregistry.operator.openshift.io/cluster patched
```

You can delete the default pvc/image-registry-storage after that if it has been created.
