### ISSUE TITLE
Disable docker redirect for S3 buckets

### ISSUE THREAD

**Issue by gfvirga** [openshift/cluster-image-registry-operator#393]
Hello,

I have setup an Openshift cluster with the "4.2.0-0.nightly-2019-09-18-114152" I was able to create a registry using our internal S3 service and it does not error when pushing to the registry, but it errors out while pulling and I was suspecting it is related to the docker redirect https://github.com/openshift/cluster-image-registry-operator/pull/385 is there any work around for this pull request?

Failed to pull image "image-registry.openshift-image-registry.svc:5000/gabetest/dotnet@sha256:8a223cf1954a312f081c0630399f28db00264391dbf51ff10296ec813154cebe": rpc error: code = Unknown desc = Error parsing image configuration: Get https://example.com:9021/ose-dev01_b/docker/registry/v2/blobs/sha256/54/5465861b01c736c2d7721ca4ef3f906718648b5e63f0aa21aa85d0cda262dfad/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ose-dev01%2F20190926%2Flocal%2Fs3%2Faws4_request&X-Amz-Date=20190926T154746Z&X-Amz-Expires=1200&X-Amz-SignedHeaders=host&X-Amz-Signature=1d5a2c62572eff3189aa22ecbadcd39068e6d7cdaec42150c53e03ac5fd25d15: remote error: tls: handshake failure

**Comment by bparees** [comment]
I don't believe it can be disabled currently(without taking the registry out of operator management which means your cluster is unsupported), but it is being fixed.... @dmage @adambkaplan did that change make 4.2.0, or will it be backported to 4.2.x?

**Comment by adambkaplan** [comment]
#385 will fix, currently in progress

**Comment by steveteuber** [comment]
You can only work around this issue when you set the `cluster-image-registry-operator` to `unmanaged` and then override the container image in the `cluster-image-registry-operator` deployment.

Setting `cluster-image-registry-operator` to unmanaged:
```
$ oc get clusterversion version -o yaml
...
spec:
  overrides:
  - group: apps/v1
    kind: Deployment
    name: cluster-image-registry-operator
    namespace: openshift-image-registry
    unmanaged: true
```

Override `cluster-image-registry-operator` container image:
```
$ oc patch deployment cluster-image-registry-operator -n openshift-image-registry -p '{
  "spec": {
    "template": {
      "spec": {
        "containers": [
          {
            "name": "cluster-image-registry-operator",
            "image": "docker.io/steveteuber/cluster-image-registry-operator:redirect"
          }
        ]
      }
    }
  }
}'
```

Disable `redirect` and route all data through the `registry`:
```
$ oc get configs.imageregistry.operator.openshift.io cluster -o yaml
...
spec:
  disableRedirect: true
```

**Comment by gfvirga** [comment]
This worked. Thank you very much.

We are looking forward for this fix!
