### ISSUE TITLE
progressing status is wrong

### ISSUE THREAD

**Issue by bparees** [openshift/cluster-image-registry-operator#43]
both the image-registry resource and the clusteroperator resource are reporting "progressing=true" when the deployment is complete.

The deployment itself reports:
```
  - lastTransitionTime: 2018-10-22T15:18:03Z
    lastUpdateTime: 2018-10-22T15:18:31Z
    message: ReplicaSet "image-registry-7cbbc9dc8c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
```

So either this is a misunderstanding on our part of what that means, or deployments have a bug in which they should be setting progressing to false/completed=true.

Certainly the "message: ReplicaSet "image-registry-7cbbc9dc8c" has successfully progressed." would imply this might be a deployments bug.

/assign @legionus

**Comment by bparees** [comment]
correction, only the image-registry resource is reporting progressing.  The clusteroperator shows progressing=false, which makes sense since its logic is driven by the # of replicas (though i think that logic is wrong and we need to discuss it)

**Comment by gabemontero** [comment]
If a fix gets in before the demo on Wednesday I'll try to include it.

**Comment by legionus** [comment]
@bparees Do you have data on the number of replicas in the deployment status?

**Comment by bparees** [comment]
It was 1.

Ben Parees | OpenShift

**Comment by legionus** [comment]
But should be more than one or is it the number that you specified in the image-registry custom resource ?

**Comment by legionus** [comment]
> But should be more than one or is it the number that you specified in the image-registry custom resource ?

It does not matter.

**Comment by bparees** [comment]
> But should be more than one or is it the number that you specified in the image-registry custom resource ?

it was 1, and it should be 1 (1 was the requested number)

**Comment by gabemontero** [comment]
FYI I was able to cut a new demo video using the fix from https://github.com/openshift/cluster-image-registry-operator/pull/44 and the `Progressing` condition showed what we expected.

**Comment by bparees** [comment]
excellent!
