### ISSUE TITLE
Support for third party S3 implementations

### ISSUE THREAD

**Issue by slauger** [openshift/cluster-image-registry-operator#485]
Hi,

it would be great if the cluster-image-registry-operator would support third party implementations of the S3 protocol (e.g. via https://github.com/minio/minio). This would allow users to use their own S3 service instead of AWS.

This would be particularly helpful in isolated (enterprise) environments (e.g. VMware vSphere does not provide a RWX storage).

**Comment by adambkaplan** [comment]
@slauger technically anyone can supply their own S3 configuration - as long as the AWS credentials are set in the user private config [1], and the bucket, region, and custom region endpoint are set on the operator config [2] any "S3 complaint" storage solution could be used.

Today AWS S3 is the only storage backend that we use to test the S3 storage options.

[1] https://github.com/openshift/cluster-image-registry-operator#image-registry-private-configuration-user-secret
[2] https://github.com/openshift/cluster-image-registry-operator/blob/master/vendor/github.com/openshift/api/imageregistry/v1/types.go#L145-L157

**Comment by slauger** [comment]
Hi @adambkaplan,

thanks for your hint. That was very helpful. I guess using a S3 compliant storage for the registry (on a VMware vSphere installation) is highly unsupported by RedHat?

Anyways, I have a customer with a S3 storage solution based on Ceph (via Object Gateway). I'll try to connect the registry to it and see what happens.

**Comment by dmage** [comment]
@slauger I wouldn't say that it's "highly unsupported". If your storage is S3-compatible (is supported by aws-sdk-go), it should work. If it doesn't, feel free to open bugs.

That said, we can't guarantee that your storage will work nicely with the image registry. We didn't test it and in the past there were "S3-compatible" storages that had problems with aws-sdk-go.

**Comment by tux-o-matic** [comment]
OCP 4 comes with Noobaa as part of the OCS. So if it's not tested or even working, the documentation should explicitly state: when using OCS for the Registry, use the CephFS storage type and not Noobaa's S3 API.

**Comment by adambkaplan** [comment]
@tux-o-matic we do have an R&D item on our backlog to add 1st class support for Noobaa/MCG [1]. Since this feature is still tech preview in OCS 4.2, provisioning Ceph via a PVC is the recommended solution. 

[1] https://issues.redhat.com/browse/DEVEXP-506
(note - link may not be fully public)

**Comment by dmage** [comment]
Feel free to open a new issue if the operator doesn't work with a particular S3-compatible implementation.
