### ISSUE TITLE
Uninstall procedure

### ISSUE THREAD

**Issue by dmage** [openshift/cluster-image-registry-operator#66]
We need a mechanism that will allow us to remove the registry. We have the ManagementState removed, but there is no indication of the removal progress. I can't delete the custom resource because the operator will re-bootstrap it.

I need this because I want to uninstall the operator and removed everything that was generated by the operator.

**Comment by bparees** [comment]
the status "progressing" should reflect this information.

progressing=true - we are deleting the registry
progressing=false - we are done deleting the registry

Not sure how to handle the race condition between the time the user marks the resource removed, and the time the status gets updated to progressing=true, however.

i'm not entirely averse to another status condition "Removed=true/false" which could be updated when the removal was completed and when registries are created.
