### ISSUE TITLE
Question: Is it possible to have more than one instance of the operator deployed in a cluster?

### ISSUE THREAD

**Issue by oswcab** [openshift/cluster-image-registry-operator#666]
The use case would be to separate images from different projects and to handle different sets of credentials.

**Comment by bparees** [comment]
no it is not possible because, among other reasons, the registry uses cluster scoped resources to store metadata about the images it contains.

**Comment by bparees** [comment]
that said, you can already constrain access to images in the registry based on standard openshift RBAC permissions, such as granting permission by namespace, and you can generate new service accounts for additional cred management.  So you should not need separate instances to achieve that goal, unless i'm not understanding it.

**Comment by oswcab** [comment]
OK, that answer my doubts. Thanks a lot for your answer.
