### ISSUE TITLE
world-writable without sticky bit in `/etc/pki/ca-trust/extracted/edk2` etc

### ISSUE THREAD

**Issue by cgwalters** [openshift/cluster-image-registry-operator#744]
See https://issues.redhat.com/browse/CMP-1179

Basically scanning the host (and recursing into the mounted containers) it seems like the cert dirs in the container end up world-writable.

I think it may be this code https://github.com/openshift/cluster-image-registry-operator/blob/11278d447c23f8248be7f35ef49e0ad6c29d144a/pkg/resource/podtemplatespec.go#L438

But as I note there it may actually be a crio bug.

**Comment by dmage** [comment]
This directory is world-writable because entrypoint script should be able to add user-provided CAs into the container's trust store. We achieved that by mounting emptyDir (i.e. tmpfs) on top of /etc/pki/ca-trust/extracted. Why should it have the sticky bit?
