### ISSUE TITLE
s3 bucket management 

### ISSUE THREAD

**Issue by bparees** [openshift/cluster-image-registry-operator#79]
Follow up to https://github.com/openshift/cluster-image-registry-operator/pull/52 to resolve the items described in:
https://github.com/openshift/cluster-image-registry-operator/pull/52#discussion_r234775884

You need to ensure that on re-sync, we are making sure the bucket exists. That means a few things:

* Adding a condition on the registry resource that indicates when we have successfully created the bucket (we should not be deploying the registry until we are sure we created the bucket)
* a mechanism for ensuring that if the S3 bucket name changed, the condition is cleared until we create the new bucket.

**Comment by coreydaley** [comment]
@bparees Can you please clarify which resource should get the conditions?

**Comment by bparees** [comment]
@coreydaley the registry custom resource.

**Comment by bparees** [comment]
> a mechanism for ensuring that if the S3 bucket name changed, the condition is cleared until we create the new bucket.

this also means you need to store the current bucket name in .status somewhere so you can recognize when it changes.

**Comment by bparees** [comment]
(you should probably just store the entire Storage struct in status so you can detect changes)

**Comment by coreydaley** [comment]
> (you should probably just store the entire Storage struct in status so you can detect changes)

I was actually considering that earlier, that's what i will go ahead and do
