### ISSUE TITLE
No logs in the cluster-image-registry-operator pod?

### ISSUE THREAD

**Issue by coreydaley** [openshift/cluster-image-registry-operator#85]
After the image registry operator pod comes up I don't see any logs displayed (when running oc get logs pod/<pod>), not even the output from printversion() that should happen.

Is there a way to set the loglevel with klog also? (debug vs info)

Am I missing something or are the logs not working after the refactor to use klog?

**Comment by bparees** [comment]
@legionus when you fix this please add an e2e that confirms logging is working also.

**Comment by legionus** [comment]
Fixed
