### ISSUE TITLE
Helm chart for cluster-image-registry-operator

### ISSUE THREAD

**Issue by jcpunk** [openshift/cluster-image-registry-operator#883]
When deploying things to my cluster I like to have helm charts so I can specifically select exactly which release is loaded and review what is running in my production clusters.

**Comment by bparees** [comment]
this component is managed by the ClusterVersionOperator, as part of the openshift container platform release payload.  It is not expected that you would deploy it yourself or deploy a version of it that differs from what was in the OCP release payload that defines the overall version of your cluster.
