### ISSUE TITLE
cluster s3 config should not stomp local secret config

### ISSUE THREAD

**Issue by bparees** [openshift/cluster-image-registry-operator#99]
Today we copy s3 config from the cluster, into the secret in the image-registry namespace, and then drive that into the registry deployment.

Instead the registry operator should be:

1) checking if there is a local secret.  If so use it.
2) If not, check if there is cluster-wide s3 config, if so, use it directly (set it on the registry deployment, don't copy it into a local secret)

We also need to be watching (2) for changes/resyncing it when there is no local secret.

**Comment by coreydaley** [comment]
@bparees I just want to be sure that I understand what we want to do here.

1.)  Are we going to look for the same secret name that we were previously creating? Or come up with a new secret name that we will look for in the openshift-image-registry namespace?
2.)  We are no longer going to create the "image-registry-private-configuration", and instead set the environment variables directly on the image registry deployment "with plain text values" instead of secret key refs.

**Comment by bparees** [comment]
1) for now, same secret name we were previously creating.  we *may* want/need to make the name (but not the namespace) configurable in the future, but for now i can accept a hardcoded secret name.  (we are both talking about the "image-registry-private-configuration" secret, right?)

2) hm.  I didn't realize we were using secret key refs today.  That changes things.

So let me start over here:  The problem we need to solve is that normally we expect to get the credentials from the kube-system namespace(or where-ever it is that we're grabbing them from today).  But we *also* need a way for the user say to "no no, *here* are the credentials I want you to use".  And if they do that, we should ignore the kube-system credentials and use the credentials they provided instead.

My understanding of how it works today is:  we copy the kube-system credentials into the private-configuration secret, and then ref it from the registry pod.  Which means there's no way for the user to supply their own credentials, because we'll keep overwriting what is in private-configuration, with the value from the installer (or we should be).

Honestly the simplest solution might be to simply have/allow two secrets:

1) the one we populate from the installer value
2) one the user can create.  If the user-controlled one exists, we prefer the credentials that exist there.

Does that make sense (both the problem and solution?)

**Comment by coreydaley** [comment]
1.)  Yep, we are both talking about the same secret

Yep, that all makes sense and actually makes it easier.
can we call the user configurable secret "image-registry-private-configuration-user" vs the one we create "image-registry-private-configuration"?

**Comment by bparees** [comment]
> can we call the user configurable secret "image-registry-private-configuration-user" vs the one we create "image-registry-private-configuration"?

works for me.

bear in mind we may reach a point where we are pulling some keys from one and some keys from the other, so the logic can't just be "if secret X exists, use it".

**Comment by coreydaley** [comment]
Actually, I think i have that backwards.
we need to have a secret called something like "aws-creds" in the openshift-image-registry namespace, because we are providing overrides for the kube-system/aws-creds file, not the image-registry-private-configuration secret.

**Comment by coreydaley** [comment]
Which would also allow someone to setup s3 storage even if they are not running on aws (potentially), which is I think what we want at some point in the future

**Comment by bparees** [comment]
> we need to have a secret called something like "aws-creds" in the openshift-image-registry namespace, because we are providing overrides for the kube-system/aws-creds file, not the image-registry-private-configuration secret.

you can look at it different ways/overriding at different points.  since i don't want to have N different override secrets for all the different platforms/cred types, i'd rather just say "if you don't want to use the creds we discovered on the cluster, put your creds in private-configuration-user and we'll use that as our first discovery source"

we can discuss this a little more during planning tomorrow.

> Which would also allow someone to setup s3 storage even if they are not running on aws (potentially), which is I think what we want at some point in the future

No, they would do that by putting their AWS creds into image-registry-private-configuration-user.

**Comment by coreydaley** [comment]
got it.  thanks
